# Generated by Django 5.1 on 2024-08-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Apellido', models.CharField(max_length=20)),
                ('Usuario', models.CharField(max_length=25, unique=True)),
                ('Correo', models.CharField(max_length=50, unique=True)),
                ('Contraseña', models.CharField(max_length=20)),
                ('Ncuenta', models.PositiveBigIntegerField()),
            ],
        ),
    ]
