# Generated by Django 5.1 on 2024-08-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_clase_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='codigo',
        ),
    ]
