# Generated by Django 5.1 on 2024-08-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_remove_clase_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
