# Generated by Django 5.1 on 2024-08-23 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0005_comentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
