# Generated by Django 5.1 on 2024-08-24 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0008_comentario_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='clase',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='clases',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Clase',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
