from django.urls import path
from . import views

urlpatterns = [
    path('', views.inicio_sesion, name='inicio_sesion'),
    path('inicio.html', views.inicio, name='inicio'),
    path('horario.html', views.horario, name='horario'),
    path('inicio_sesion.html', views.inicio_sesion, name='inicio_sesion'),
    path('registro.html', views.registro, name='registro'),
    path('respuestaRegistro/', views.respuestaRegistro, name='respuestaRegistro'),
    path('respuestaLogin/', views.respuestaLogin, name='respuestaLogin'),
    path('perfil.html', views.perfil, name='perfil'),
    path('logout/', views.logout, name='logout'),
    path('recomendaciones.html', views.recomendaciones, name='recomendaciones'),
    path('agregar-clase/', views.agregar_clase, name='agregar_clase'),
    path('mostrar-horario/', views.mostrar_horario, name='mostrar_horario'),
    path('eliminar-clase/', views.eliminar_clase, name='eliminar_clase'),
    path('EG-011.html', views.Español, name='EG-011'),
    path('Electiva1.html', views.Electiva1, name='Electiva1'),
    path('IN-101.html', views.InglesI, name='IN-101'),
    path('IN-102.html', views.InglesII, name='IN-102'),
    path('IS-110.html', views.Introduccion, name='IS-110'),
    path('MM-110.html', views.MateI, name='MM-110'),
    path('MM-111.html', views.Geometria, name='MM-111'),
    path('MM-201.html', views.CalculoI, name='MM-201'),
    path('MM-202.html', views.CalculoII, name='MM-202'),
    path('MM-211.html', views.Vectores, name='MM-211'),
    path('MM-314.html', views.Programacion1, name='MM-314'),
    path('CS-101.html', views.Sociologia, name='CS-101'),
    path('guardar_comentario/', views.guardar_comentario, name='guardarComentario'),
    path('mostrar_comentario/', views.mostrar_comentario, name='mostrarComentario'),
    path('Plan_Estudio.html', views.PlanEstudio, name='PlanEstudio'),
    path('incrementar_likes/', views.incrementar_likes, name='incrementar_likes'),
]
